### ISSUE TITLE
Vlan CNI switch=ipvlan ipvlan_mode=l3, l3s do not send gratuitous arp

### ISSUE THREAD

**Issue by blue-troy** [tkestack/galaxy#128]
[in code](https://github.com/tkestack/galaxy/blob/v1.0.8/cni/k8s-vlan/k8s_vlan.go#L124)

```go
if d.IpVlanMode == "l3" || d.IpVlanMode == "l3s" {
		_ = utils.SendGratuitousARP(d.Device, result.IP4.IP.IP.String(), "", d.GratuitousArpRequest)
		return nil
	}
```

we want to send gratuitous arp.but we [in code](https://github.com/tkestack/galaxy/blob/v1.0.8/pkg/network/vlan/vlan.go#L128)

```go
if d.MacVlanMode() || d.IPVlanMode() {
		return nil
	}
	if d.PureMode() {
		if err := d.initPureModeArgs(); err != nil {
			return err
		}
		return utils.EnableNonlocalBind()
	}
```
wo did not set EnableNonlocalBind for ipvlan l3 l3s mode. and we ignore the utils.SendGratuitousARP error result.

**Comment by blue-troy** [comment]
if SendGratuitousARP problem solved,there till will be a arp cache problem. but i think we should solve this problem first.

**Comment by chenchun** [comment]
@blue-troy with you patch, is the problem solved?

**Comment by blue-troy** [comment]
> @blue-troy with you patch, is the problem solved?
in my test environment,the problem solved.did not you?

**Comment by chenchun** [comment]
I don't have an environment to test it. I'm closing the issue, thanks for reporting.
