### ISSUE TITLE
Remove database ipam

### ISSUE THREAD

**Issue by chenchun** [tkestack/galaxy#15]
[Database ipam](https://github.com/tkestack/galaxy/blob/master/pkg/ipam/floatingip/store.go) was implemented when k8s doesn't support CRD. Now that CRD ipam is stable enough, we can remove database ipam now.

**Comment by gongguan** [comment]
While galaxy could support multiple netlink, can we delete second ipam which seems weired?

**Comment by chenchun** [comment]
multiple CNI?

Second ipam is badly implemented now. But we still using it in some clusters, better if we can re-design this feature.

**Comment by gongguan** [comment]
> multiple CNI? multiple CNI does not resolve how to get allocate multiple IPs?

get
